env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-essential
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
  extraFileExtensions: [".vue"]
plugins:
  - vue
  - "@typescript-eslint"
rules: 
  "@typescript-eslint/explicit-function-return-type": "off"
overrides: []